[project]
name = "zocha-cdp"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "dbt-core>=1.10.3",
    "dbt-duckdb>=1.9.4",
    "duckdb>=1.3.1",
    "pip>=25.1.1",
    "sqlfluff>=3.4.2",
    "sqlfluff-templater-dbt>=3.4.2",
]
